version: '3'
services:
  app:
    build: .
    ports:
      - 8080:8080
    environment:
      PG_HOST: ${PG_HOST}
      PG_LOGIN: ${PG_LOGIN}
      PG_PASS: ${PG_PASS}
      PG_DB: ${PG_DB}
      HIKARI_BOT_TOKEN: ${HIKARI_BOT_TOKEN} 
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${PG_LOGIN}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: ${PG_DB}
    ports:
      - 5433:5432
    volumes:
      - ./data:/var/lib/postgresql/data